### ISSUE TITLE
Use Cases for Suspending an Account

### ISSUE THREAD

**Issue by Jonathan-Fort** [Jonathan-Fort/ISS-Project#3]
Account Suspensions are our "this user is banned" system. We need to determine what all would cause an account to become suspended. Would the specific case be a temporary suspension, or permanent?

**Comment by originalnizari** [comment]
We mandate logins every 30 days. I think A flag would be in order, I don't see this being an effective use of automatic suspension. Indeed part of the reason for the policy to exist is to keep people coming back, not the other way around!
Start a new use case for flagging users, this is a new system that enjin lacks, AFAIK.

**Comment by Phanstar0** [comment]
How about one loses access to all but their most basic of functions if they haven't logged in after 30-60 days. Like the only things they can do is see their profile with the lose of functions status and maybe the general forum pages. Annousments, general conversations, and the like.

**Comment by Jonathan-Fort** [comment]
So what's the reasons this may be useful? We've talked about doing it, but not _why._
